name: build and test

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java: [ 8, 11 ]

    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup-java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: maven
      uses: GabrielBB/xvfb-action@v1
      with:
        run: mvn --batch-mode test verify
    - name: test report
      uses: dorny/test-reporter@v1
      if: ${{ runner.os == 'Linux' && matrix.java == 11 }}
      with:
        reporter: java-junit
        path: 'target/surefire-reports/TEST-*.xml'
    - name: coverage report
      uses: codecov/codecov-action@v1.5.0
      if: ${{ runner.os == 'Linux' && matrix.java == 11 }}
      with:
        file: target/site/jacoco/jacoco.xml
