name: build and test

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java: [ 8, 11, 13 ]

    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: xvfb-action
      uses: GabrielBB/xvfb-action@v1
    - name: setup-java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: maven
      run: mvn --batch-mode test verify
